crumbs.settings:
  type: mapping
  label: Settings
  mapping:
    crumbs_show_current_page:
      type: boolean
    crumbs_show_front_page:
      type: boolean
    crumbs_minimum_trail_items:
      type: integer
    crumbs_separator:
      type: string
    crumbs_separator_span:
      type: boolean
    crumbs_home_link_title:
      type: string
